services:
  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_TSL_AUTH: true
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db